"""Static hub content. Swap for a real store when the intake/marketplace services exist."""

from .models import Domain, Link, Notification, Pillar, SearchResult, Section


DOMAINS = [
    Domain(id="all", name="All domains"),
    Domain(id="cards", name="Cards"),
    Domain(id="lending", name="Lending"),
    Domain(id="collections", name="Collections"),
    Domain(id="fraud", name="Fraud & Risk"),
    Domain(id="operations", name="Operations"),
]

PILLARS = [
    Pillar(
        id="marketplace",
        number=1,
        title="AI Marketplace and Discovery",
        short_title="Discover",
        card_title="Discover AI",
        description="Find trusted solutions, agents and reusable capabilities.",
        icon="search",
        tone="blue",
        priority=True,
        primary_links=[
            Link(label="AI solutions", href="/marketplace/solutions"),
            Link(label="Agents", href="/marketplace/agents"),
            Link(label="Capabilities", href="/marketplace/capabilities"),
        ],
        secondary_links=[Link(label="Search by business domain", href="/marketplace?by=domain")],
        cta_label="Explore marketplace",
        cta_href="/marketplace",
        sections=[
            Section(title="AI solutions", href="/marketplace/solutions", blurb="Approved, production-ready AI solutions you can adopt today."),
            Section(title="Agents", href="/marketplace/agents", blurb="Reusable agents with owners, SLAs and usage guidance."),
            Section(title="Capabilities", href="/marketplace/capabilities", blurb="Platform capabilities such as document intelligence, summarisation and search."),
        ],
    ),
    Pillar(
        id="prompts",
        number=2,
        title="Prompts & Skills Library",
        short_title="Prompts & Skills",
        description="Find reusable prompts and skills.",
        icon="library",
        tone="blue",
        cta_label="Browse library",
        cta_href="/library",
        sections=[
            Section(title="Prompt library", href="/library/prompts", blurb="Vetted prompts organised by task and business domain."),
            Section(title="Skills", href="/library/skills", blurb="Packaged skills you can attach to agents and copilots."),
            Section(title="Submit a prompt", href="/library/submit", blurb="Share a prompt that worked for your team."),
        ],
    ),
    Pillar(
        id="learning",
        number=3,
        title="AI Learning and Enablement",
        short_title="Learning",
        card_title="Learning",
        description="Find learning and guidance for your role.",
        icon="graduation",
        tone="teal",
        priority=True,
        primary_links=[
            Link(label="Catalog", href="/learning"),
            Link(label="Role-based paths", href="/learning?path=business"),
        ],
        secondary_links=[
            Link(label="Getting started", href="/learning?path=getting-started"),
            Link(label="Best practices", href="/learning/best-practices"),
            Link(label="Product docs", href="/learning/docs"),
            Link(label="Quick reference", href="/learning/quick-reference"),
        ],
        cta_label="Explore learning",
        cta_href="/learning",
        sections=[
            Section(title="Learning catalog", href="/learning", blurb="Courses, labs and certifications for every level."),
            Section(title="Role-based paths", href="/learning?path=business", blurb="Curated paths for analysts, engineers, managers and operations."),
            Section(title="Getting started", href="/learning?path=getting-started", blurb="Your first hour with AI at CreditWiz."),
            Section(title="Best practices", href="/learning/best-practices", blurb="How our teams get reliable results."),
            Section(title="Product docs", href="/learning/docs", blurb="Reference documentation for hub tools."),
            Section(title="Quick reference", href="/learning/quick-reference", blurb="One-page cheat sheets."),
        ],
    ),
    Pillar(
        id="intake",
        number=4,
        title="AI Intake and Enablement",
        short_title="AI Requests",
        description="Submit an AI use case.",
        icon="clipboard",
        tone="purple",
        cta_label="Start a request",
        cta_href="/intake/new",
        sections=[
            Section(title="Start a request", href="/intake/new", blurb="Describe a use case and route it for review."),
            Section(title="My requests", href="/intake/mine", blurb="Track the status of use cases you submitted."),
            Section(title="Review queue", href="/intake/queue", blurb="For reviewers: use cases awaiting a decision."),
        ],
    ),
    Pillar(
        id="governance",
        number=5,
        title="Governance and Trust Center",
        short_title="Governance",
        description="Find responsible AI guidance.",
        icon="shield",
        tone="teal",
        cta_label="View guidance",
        cta_href="/governance",
        sections=[
            Section(title="Policies", href="/governance/policies", blurb="Acceptable use, data handling and model risk policies."),
            Section(title="Responsible AI guidance", href="/governance/responsible-ai", blurb="Fairness, transparency and human-in-the-loop expectations."),
            Section(title="Model inventory", href="/governance/inventory", blurb="Every approved model, its owner and its risk tier."),
        ],
    ),
    Pillar(
        id="knowledge",
        number=6,
        title="Enterprise Knowledge and Context Foundation",
        short_title="Knowledge",
        description="Explore shared enterprise knowledge.",
        icon="database",
        tone="blue",
        cta_label="Explore knowledge",
        cta_href="/knowledge",
        sections=[
            Section(title="Knowledge sources", href="/knowledge/sources", blurb="Connected repositories, wikis and document stores."),
            Section(title="Context packs", href="/knowledge/context-packs", blurb="Curated context bundles for grounding agents."),
            Section(title="Data glossary", href="/knowledge/glossary", blurb="Shared definitions for business terms."),
        ],
    ),
    Pillar(
        id="community",
        number=7,
        title="Community and Collaboration",
        short_title="Community",
        card_title="Community",
        description="Ask questions, share knowledge and find experts.",
        icon="users",
        tone="blue",
        priority=True,
        primary_links=[
            Link(label="Forums", href="/community/forums"),
            Link(label="SME directory", href="/community/experts"),
            Link(label="FAQs", href="/community/faqs"),
        ],
        secondary_links=[
            Link(label="Announcements", href="/community/announcements"),
            Link(label="Success stories", href="/community/stories"),
        ],
        cta_label="Open community",
        cta_href="/community",
        sections=[
            Section(title="Forums", href="/community/forums", blurb="Ask questions and share what you have learned."),
            Section(title="SME directory", href="/community/experts", blurb="Find subject-matter experts by domain."),
            Section(title="FAQs", href="/community/faqs", blurb="Answers to the most common questions."),
            Section(title="Announcements", href="/community/announcements", blurb="What changed in the hub this month."),
            Section(title="Success stories", href="/community/stories", blurb="How teams are getting value from AI."),
        ],
    ),
    Pillar(
        id="insights",
        number=8,
        title="Operational Intelligence and Value Realization",
        short_title="Insights",
        description="Explore adoption and value insights.",
        icon="chart",
        tone="teal",
        cta_label="View insights",
        cta_href="/insights",
        sections=[
            Section(title="Adoption dashboard", href="/insights/adoption", blurb="Who is using what, and how often."),
            Section(title="Value realisation", href="/insights/value", blurb="Hours saved, cases resolved and outcomes delivered."),
            Section(title="Quality and safety", href="/insights/quality", blurb="Evaluation results and incident trends."),
        ],
    ),
    Pillar(
        id="platform",
        number=9,
        title="AI Hub Platform Enablement",
        short_title="Platform",
        description="Access platform support and services.",
        icon="settings",
        tone="purple",
        cta_label="Open platform",
        cta_href="/platform",
        admin_only=True,
        sections=[
            Section(title="Access management", href="/platform/access", blurb="Roles, groups and entitlements."),
            Section(title="Integrations", href="/platform/integrations", blurb="Connected systems and API keys."),
            Section(title="Settings", href="/platform/settings", blurb="Hub-wide configuration."),
        ],
    ),
]

SEARCH_INDEX = [
    SearchResult(kind="solution", title="Credit decision explainer", href="/marketplace/solutions/decision-explainer"),
    SearchResult(kind="solution", title="Statement dispute triage", href="/marketplace/solutions/dispute-triage"),
    SearchResult(kind="agent", title="Collections outreach agent", href="/marketplace/agents/collections-outreach"),
    SearchResult(kind="agent", title="Fraud case summariser", href="/marketplace/agents/fraud-summariser"),
    SearchResult(kind="prompt", title="Customer email tone rewrite", href="/library/prompts/email-tone"),
    SearchResult(kind="prompt", title="Policy Q&A grounding prompt", href="/library/prompts/policy-qa"),
    SearchResult(kind="learning", title="Responsible AI fundamentals", href="/learning/videos/responsible-ai-fundamentals"),
    SearchResult(kind="learning", title="Prompting for analysts", href="/learning/videos/prompting-for-analysts"),
]

NOTIFICATIONS = [
    Notification(
        id="n-1",
        title="Your intake request was approved",
        body="Statement dispute triage is cleared for pilot in Collections.",
        href="/intake/mine",
        created_at="2026-09-08T09:12:00Z",
    ),
    Notification(
        id="n-2",
        title="New course: Responsible AI fundamentals",
        body="Required for anyone building or approving agents.",
        href="/learning/videos/responsible-ai-fundamentals",
        created_at="2026-09-07T15:40:00Z",
    ),
    Notification(
        id="n-3",
        title="Forum reply on your question",
        body="An SME answered your question about grounding an agent on policy documents.",
        href="/community/forums",
        created_at="2026-09-06T11:05:00Z",
    ),
]
